"""Add is_rejected to User

Revision ID: 1e61f61f8738
Revises: 
Create Date: 2025-05-25 14:31:57.033446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e61f61f8738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_uuid',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
        batch_op.drop_column('is_rejected')

    # ### end Alembic commands ###
