"""add file fields to message model

Revision ID: 63d5e19c7749
Revises: aab5c3a31684
Create Date: 2025-11-05 03:39:52.751997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63d5e19c7749'
down_revision = 'aab5c3a31684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 먼저 NULL room_uuid 값들을 정리
    op.execute("UPDATE messages SET room_uuid = NULL WHERE room_uuid = ''")
    
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.alter_column('read_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('message_reads_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_reads_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reader_uuid'], ['user_uuid'])
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('sender_uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        # 외래 키 제약 조건을 나중에 추가하지 않음 - room_uuid가 NULL일 수 있으므로

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('sender_uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_reads_ibfk_1'), 'messages', ['message_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('message_reads_ibfk_2'), 'users', ['reader_uuid'], ['user_uuid'], ondelete='CASCADE')
        batch_op.alter_column('read_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
